kind: pipeline
name: default

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --remote

- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.55.5
    validate: true

- name: debug
  image: alpine
  commands:
   - ls -lh
   - ls -lh themes
   - ls -lh themes/hugo-uilite
   - ls -lh public

- name: publish  
  image: plugins/gh-pages
  settings:
    pages_directory: public
    target_branch: master
    username:
      from_secret: github_username
    password:
      from_secret: github_password
