kind: pipeline
name: default

- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.55.5
    validate: true

- name: publish  
  image: plugins/gh-pages
  settings:
    pages_directory: public/