kind: pipeline
name: default

steps:
- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.55.5
    validate: true

- name: publish  
  image: plugins/gh-pages
  environment:
    DRONE_REMOTE_URL: "git@github.com:ok-production/ok-production.github.io.git"
  settings:
    pages_directory: public/
    username: omtx
    ssh_key:
      from_secret: github_ssh_key
