kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive

- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.55.5
    validate: true

- name: publish  
  image: plugins/gh-pages
  settings:
    pages_directory: public
    target_branch: master
    username:
      from_secret: github_username
    password:
      from_secret: github_password
